// LibreSprite | Copyright (C) 2024 LibreSprite contributors
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "app/file/file.h"
#include "app/file/file_format.h"
#include "app/file/format_options.h"
#include "base/cfile.h"
#include "base/file_handle.h"
#include "doc/doc.h"

#include <map>
#include <vector>
#include <algorithm>

namespace app {

using namespace base;

namespace {
  struct SpecColor {
    int r, g, b, bright, code;
  };
  const SpecColor spec_palette[] = {
    {0x00, 0x00, 0x00, 0, 0}, // Black
    {0x00, 0x00, 0xD7, 0, 1}, // Blue
    {0xD7, 0x00, 0x00, 0, 2}, // Red
    {0xD7, 0x00, 0xD7, 0, 3}, // Magenta
    {0x00, 0xD7, 0x00, 0, 4}, // Green
    {0x00, 0xD7, 0xD7, 0, 5}, // Cyan
    {0xD7, 0xD7, 0x00, 0, 6}, // Yellow
    {0xD7, 0xD7, 0xD7, 0, 7}, // White
    {0x00, 0x00, 0x00, 1, 0}, // Black (Bright)
    {0x00, 0x00, 0xFF, 1, 1}, // Blue (Bright)
    {0xFF, 0x00, 0x00, 1, 2}, // Red (Bright)
    {0xFF, 0x00, 0xFF, 1, 3}, // Magenta (Bright)
    {0x00, 0xFF, 0x00, 1, 4}, // Green (Bright)
    {0x00, 0xFF, 0xFF, 1, 5}, // Cyan (Bright)
    {0xFF, 0xFF, 0x00, 1, 6}, // Yellow (Bright)
    {0xFF, 0xFF, 0xFF, 1, 7}  // White (Bright)
  };

  int get_zx_color_index(int r, int g, int b) {
    int best_match = 0;
    int min_dist = 255*255*3 + 1;
    for (int i=0; i<16; i++) {
      int dr = spec_palette[i].r - r;
      int dg = spec_palette[i].g - g;
      int db = spec_palette[i].b - b;
      int dist = dr*dr + dg*dg + db*db;
      if (dist < min_dist) {
        min_dist = dist;
        best_match = i;
      }
    }
    return best_match;
  }
}

class AsmFormat : public FileFormat {
  const char* onGetName() const override { return "asm"; }
  const char* onGetExtensions() const override { return "asm"; }
  int onGetFlags() const override {
    return
      FILE_SUPPORT_SAVE |
      FILE_SUPPORT_RGB |
      FILE_SUPPORT_RGBA |
      FILE_SUPPORT_INDEXED |
      FILE_SUPPORT_GRAY |
      FILE_SUPPORT_SEQUENCES;
  }

  bool onLoad(FileOp* fop) override { return false; }
  bool onSave(FileOp* fop) override;
};

static FileFormat::Regular<AsmFormat> ff{"asm"};

bool AsmFormat::onSave(FileOp* fop)
{
  const Image* image = fop->sequenceImage();
  FileHandle handle(open_file_with_exception(fop->filename(), "w"));
  FILE* f = handle.get();

  fprintf(f, "; This file was generated by LibreSprite\n");
  fprintf(f, "; Do not edit\n\n");
  fprintf(f, ";sprite_format 4\n\n");

  auto get_rgba = [&](int x, int y, int& r, int& g, int& b, int& a) {
    int c = get_pixel(image, x, y);
    switch (image->pixelFormat()) {
      case IMAGE_GRAYSCALE: {
        int v = graya_getv(c);
        r = v; g = v; b = v; a = graya_geta(c);
        break;
      }
      case IMAGE_RGB:
        r = rgba_getr(c);
        g = rgba_getg(c);
        b = rgba_getb(c);
        a = rgba_geta(c);
        break;
      case IMAGE_INDEXED: {
        int pr, pg, pb, pa;
        if (c < fop->sequenceGetNColors()) {
           fop->sequenceGetColor(c, &pr, &pg, &pb);
           fop->sequenceGetAlpha(c, &pa);
           r = pr; g = pg; b = pb; a = pa;
        } else {
           r = g = b = a = 0;
        }
        break;
      }
      default:
        r = g = b = a = 0;
    }
  };

  struct BlockData {
    std::vector<int> bytes;
    int attr;
    bool operator==(const BlockData& o) const {
      return attr == o.attr && bytes == o.bytes;
    }
  };
  
  std::vector<BlockData> unique_blocks;
  std::vector<int> map_indices;

  int blocks_x = (image->width() + 7) / 8;
  int blocks_y = (image->height() + 7) / 8;

  for (int by=0; by<blocks_y; by++) {
    for (int bx=0; bx<blocks_x; bx++) {
      std::map<int, int> color_counts;
      for (int y=by*8; y<(by+1)*8; y++) {
        for (int x=bx*8; x<(bx+1)*8; x++) {
          if (x >= image->width() || y >= image->height()) continue;
          int r, g, b, a;
          get_rgba(x, y, r, g, b, a);
          if (a >= 128) {
            int zx_col = get_zx_color_index(r, g, b);
            color_counts[zx_col]++;
          }
        }
      }
      
      int paper = 0; // Black default
      int ink = 7;   // White default
      
      if (!color_counts.empty()) {
        std::vector<std::pair<int, int>> counts;
        for (auto& kv : color_counts) counts.push_back({kv.second, kv.first});
        std::sort(counts.rbegin(), counts.rend());
        paper = counts[0].second;
        if (counts.size() > 1) {
          ink = counts[1].second;
        } else {
          ink = paper;
        }
      }
      
      int paper_code = spec_palette[paper].code;
      int ink_code = spec_palette[ink].code;
      int bright = spec_palette[ink].bright | spec_palette[paper].bright;
      int attr = (bright << 6) | (paper_code << 3) | ink_code;
      
      BlockData bd;
      bd.attr = attr;
      
      for (int y=by*8; y<(by+1)*8; y++) {
        int mask = 0;
        int bmp = 0;
        for (int x=bx*8; x<(bx+1)*8; x++) {
          int bit = 7 - (x - bx*8);
          if (x >= image->width() || y >= image->height()) {
            mask |= (1 << bit); // Transparent mask
            continue;
          }
          int r, g, b, a;
          get_rgba(x, y, r, g, b, a);
          if (a < 128) {
            mask |= (1 << bit);
          } else {
            int zx_col = get_zx_color_index(r, g, b);
            if (zx_col == ink && ink != paper) {
              bmp |= (1 << bit); // Ink
            } else if (zx_col == ink && ink == paper) {
              // Same color, we can draw it as paper or ink. We use ink (1).
              bmp |= (1 << bit);
            }
          }
        }
        bd.bytes.push_back(mask);
        bd.bytes.push_back(bmp);
      }
      
      int block_index = -1;
      for (size_t i=0; i<unique_blocks.size(); i++) {
        if (unique_blocks[i] == bd) {
          block_index = i; break;
        }
      }
      if (block_index == -1) {
        block_index = unique_blocks.size();
        unique_blocks.push_back(bd);
      }
      map_indices.push_back(block_index);
    }
  }

  for (size_t i=0; i<unique_blocks.size(); i++) {
    fprintf(f, "sprite_sprite%zu:\n", i);
    fprintf(f, ";map_tile\n");
    fprintf(f, ";has_mask\n");
    fprintf(f, ";interleaved_colors\n");
    for (size_t j=0; j<8; j++) {
      fprintf(f, "    DEFB 0x%02x, 0x%02x\n", unique_blocks[i].bytes[j*2], unique_blocks[i].bytes[j*2+1]);
    }
    fprintf(f, "    DEFB 0x%02x; color attributes\n\n", unique_blocks[i].attr);
  }

  fprintf(f, "map_array:\n");
  fprintf(f, ";tile_size: %d,%d\n", blocks_x, blocks_y);

  for (int by=0; by<blocks_y; by++) {
    fprintf(f, "    DEFB ");
    for (int bx=0; bx<blocks_x; bx++) {
      fprintf(f, "0x%02x", map_indices[by*blocks_x + bx]);
      if (bx != blocks_x - 1) {
        fprintf(f, ", ");
      }
    }
    fprintf(f, "\n");
    fop->setProgress((float)(by+1) / (float)blocks_y);
  }

  if (ferror(f)) {
    fop->setError("Error writing ASM file.\n");
    return false;
  }
  return true;
}

} // namespace app
